# Generated by Django 5.2.5 on 2026-07-17 11:32

import django.core.validators
import django.db.models.deletion
import products.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(max_length=3000)),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('sale_status', models.CharField(choices=[('ON_SALE', '판매 중'), ('RESERVED', '예약'), ('SOLD', '판매 완료')], db_index=True, default='ON_SALE', max_length=12)),
                ('visibility_status', models.CharField(choices=[('PUBLIC', '공개'), ('UNDER_REVIEW', '검토 중'), ('HIDDEN', '숨김'), ('DELETED', '삭제')], db_index=True, default='PUBLIC', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visibility_status', '-created_at'], name='products_pr_visibil_1ed613_idx')],
            },
        ),
    ]
