# Generated by Django 5.2.5 on 2026-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DIGITAL', '디지털/가전'), ('FASHION', '의류/잡화'), ('LIVING', '생활/주방'), ('HOBBY', '도서/티켓/취미'), ('SPORTS', '스포츠/레저'), ('BEAUTY', '뷰티/미용'), ('ETC', '기타 중고')], db_index=True, default='ETC', max_length=12),
        ),
    ]
