# Generated by Django 5.2.5 on 2026-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample_image_path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
